export const sequential = funcs => input  => funcs.reduce((prev, func) => prev.then(func), Promise.resolve(input))
export const parallel   = funcs => input  => Promise.resolve(input).then(x => Promise.all(funcs.map(func => func(input))))
export const call       = func  => input  => Promise.resolve(input).then(func)
export const apply      = func  => inputs => Promise.all(inputs).then(xs => func.apply(undefined, xs))
export const map        = func  => inputs => Promise.all(inputs.map(call(func)))
