export const sequential = funcs => input  => funcs.reduce((prev, func) => func(prev), input)
export const parallel   = funcs => input  => funcs.map(func => func(input))
export const call       = func  => input  => func(input)
export const apply      = func  => inputs => func.apply(undefined, inputs)
export const map        = func  => inputs => inputs.map(call(func))
